version: '3'
services:

    elastic1:
        image: my-elastic:latest
        container_name: elastic1
        build:
         context: ./elastic/
         dockerfile: Dockerfile
        restart: always
        hostname: elastic1
        ports:
          - "9200:9200"
        environment:
          SERVER_ID: 1
          PEER_SERVERS: elastic2:22,elastic3:22
        volumes:
          - ./elasticsearch.yml:/elastic1/elasticsearch.yml

    elastic2:
        image: my-elastic:latest
        container_name: elastic2
        build:
         context: ./elastic/
         dockerfile: Dockerfile
        restart: always
        hostname: elastic2
        ports:
          - "9300:9200"
        environment:
          SERVER_ID: 2
          PEER_SERVERS: elastic3:22,elastic1:22
        volumes:
          - ./elasticsearch.yml:/elastic2/elasticsearch.yml

    elastic3:
        image: my-elastic:latest
        container_name: elastic3
        build:
         context: ./elastic/
         dockerfile: Dockerfile
        restart: always
        hostname: elastic3
        ports:
          - "9400:9200"
        environment:
          SERVER_ID: 3
          PEER_SERVERS: elastic2:22,elastic1:22
        volumes:
          - ./elasticsearch.yml:/elastic3/elasticsearch.yml

    kibana:
        image: my-kibana:latest
        container_name: kibana
        build:
         context: ./kibana/
         dockerfile: Dockerfile
        restart: always
        hostname: kibana
        ports:
          - "5601:5601"
        depends_on:
          - elastic1
          - elastic2
          - elastic3
        environment:
          ELASTIC_SERVERS: elastic1:9200,elastic2:9200,elastic3:9200
        volumes:
          - ./kibana.yml:/etc/kibana/kibana.yml

    filebeat:
        image: my-beat:latest
        container_name: filebeat
        build:
         context: ./filebeat/
         dockerfile: Dockerfile
        restart: always
        hostname: filebeat
        ports:
          - "5044:5044"
        depends_on:
          - elastic1
          - elastic2
          - elastic3
          - kibana
        environment:
          ELASTIC_SERVERS: elastic1:9200,elastic2:9200,elastic3:9200,kibana:5601
        volumes:
          - ./beat.yml:/etc/filebeat/filebeat.yml
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro


    proxy:
        image: my-nginx:latest
        container_name: proxy
        build:
         context: ./nginx/
         dockerfile: Dockerfile
        restart: always
        hostname: proxy
        ports:
          - "8080:80"
        environment:
           KIBANA_SERVER: kibana:5601
        depends_on:
          - kibana
        volumes:
          - ./default:/etc/nginx/nginx.conf
